#ifndef _QEMU_TIMER_H
#define _QEMU_TIMER_H

#define ARM_TIMER_BASE_ADDR    0xfe00b000UL

#define ARM_TIMER_LOAD		ARM_TIMER_BASE_ADDR + 0x400UL
#define ARM_TIMER_VALUE		ARM_TIMER_BASE_ADDR + 0x404UL
#define ARM_TIMER_CONTROL	ARM_TIMER_BASE_ADDR + 0x408UL
#define ARM_TIMER_IRQCNTL	ARM_TIMER_BASE_ADDR + 0x40CUL
#define ARM_TIMER_RAWIRQ	ARM_TIMER_BASE_ADDR + 0x410UL
#define ARM_TIMER_MSKIRQ	ARM_TIMER_BASE_ADDR + 0x404UL
#define ARM_TIMER_RELOAD	ARM_TIMER_BASE_ADDR + 0x408UL
#define ARM_TIMER_PREDIV	ARM_TIMER_BASE_ADDR + 0x408UL
#define ARM_TIMER_FREECNT	ARM_TIMER_BASE_ADDR + 0x408UL
 

void init_timer(void);
void timer_interrupt_handler(void);

#endif
