#ifndef _SYSTEM_TIMER_H
#define _SYSTEM_TIMER_H

#define SYS_TIMER_BASE_ADDR    0x7e003000UL
// #define SYS_TIMER_BASE_ADDR    0xfe203000UL
// #define SYS_TIMER_BASE_ADDR    0x20003000UL

#define SYS_TIMER_CS		SYS_TIMER_BASE_ADDR + 0x00UL
#define SYS_TIMER_CLO		SYS_TIMER_BASE_ADDR + 0x04UL
#define SYS_TIMER_CHI		SYS_TIMER_BASE_ADDR + 0x08UL
#define SYS_TIMER_C0		SYS_TIMER_BASE_ADDR + 0x0CUL
#define SYS_TIMER_C1		SYS_TIMER_BASE_ADDR + 0x10UL
#define SYS_TIMER_C2		SYS_TIMER_BASE_ADDR + 0x04UL
#define SYS_TIMER_C3		SYS_TIMER_BASE_ADDR + 0x08UL

void system_timer_init();

#endif
